import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import getConsult from "../components/getConsult";
import ChatBox from "../components/chatBox";
import "typeface-poppins";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AI Chat Consult</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>Get started by sending messages version 1.2</p>
          <div className="text-white">
            <a
              href="https://decidev22.github.io/andybaeck.io/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Team Jogger
            </a>
          </div>
        </div>
        <div className={`${styles.center} flex-row `}>
          {" "}
          <div>
            <ChatBox />
          </div>
        </div>
        <br />

        <div className="flex flex-row text-white">
          <a
            href="https://decidev22.github.io/andybaeck.io/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              My Blog <span>-&gt;</span>
            </h2>
            <p>Visit my blog and leave me a message!</p>
          </a>

          <a
            href="https://openai.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>How it works:</h2>
            <p>
              This AI chat is built with openAI API. There is no professional
              consultation behind this engineering! Please do your own research
              on the topic and only use this space to explore and get ideas.
            </p>
          </a>
          <a
            href="https://openai.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Disclaimer:</h2>
            <p>
              Please keep in mind that ChatGPT is an AI language model and its
              responses are generated based on its training data, and therefore
              may not always be accurate or appropriate.
            </p>
          </a>
          <a
            href="https://openai.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Your Data:</h2>
            <p>
              Developer does not have any access to your input data. My app only
              parses your request in a style of Life Consulting and sends it to
              OpenAI.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
